# See https://golangci-lint.run/docs/linters/configuration/
version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - wsl_v5
    - noctx
    - funcorder
    - embeddedstructfieldcheck
    - noinlineerr
    - copyloopvar
    - cyclop
    - depguard
    - dupword
    - err113
    - errname
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - intrange
    - ireturn
    - lll
    - mnd
    - musttag
    - nonamedreturns
    - paralleltest
    - recvcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - varnamelen
    - wrapcheck
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 20
    misspell:
      locale: US
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - funlen
          - goconst
          - ineffassign
          - mnd
          - noctx
          - unparam
          - unused
          - wastedassign
          - wsl
        path: _test.go
      - linters:
          - errcheck
          - gosec
        path: example_
      - linters:
          - revive
        text: 'unused-parameter: parameter'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
